### ISSUE TITLE
"a" tags with authority information under IE.

### ISSUE THREAD

**Issue by tombonner** [tombonner/jurlp#3]
The following error is thrown under IE when trying to access an "a" tag that contains a username/password in the URL:

SCRIPT14: A security problem occurred.

It seems IE blocks access to the object in this instance.

At present, this makes it impossible to parse or set a username/password on a URL using jurlp under IE.

**Comment by JohnDDuncanIII** [comment]
For whomever else comes across this error (we had a production sentry event of `セキュリティの問題が発生しました` from one of our Japanese users using `Edge 17.17134`, which brought me to https://note.kiriukun.com/entry/20190209-get-current-url-in-javascript, which then brought me here) in the future, I was able to fix this by simply invoking `element.getAttribute("href")` rather than `element.href`.

<img width="291" alt="Screen Shot 2019-11-19 at 2 30 03 PM" src="https://user-images.githubusercontent.com/9257785/69179333-5f396780-0ad9-11ea-9571-c24ac4f791d9.png">
